#ifndef _MESHDONGLE_H_
#define _MESHDONGLE_H_

/* Generated by WriteClassHeaderVisitor: Tue Nov 17 2020 09:43:16 GMT-0700 (Mountain Standard Time) */

#ifdef INCLUDE_PRIVATE
typedef struct _PhidgetMeshDongle *PhidgetMeshDongleHandle;

/* Methods */
API_PRETURN_HDR PhidgetMeshDongle_create(PhidgetMeshDongleHandle *ch);
API_PRETURN_HDR PhidgetMeshDongle_delete(PhidgetMeshDongleHandle *ch);

/* Properties */

/* Events */

#endif /* INCLUDE_PRIVATE */
#endif /* _MESHDONGLE_H_ */
